spring:
  datasource:
    url: jdbc:sqlite:./todo.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import:
      - 'classpath:api-http.yml'
jwt:
  secret: "your-256-bit-secret-your-256-bit-secret"
  expiration: 3600000